workspace/test_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#home'
  get 'about', to: 'welcome#about'
end

workspace/test_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workspace/test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

workspace/test_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def home
        
    end
    
    def about
        
    end
end

workspace/test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

workspace/test_app/app/views/welcome/about.html.erb
<h1>Hello this the about page</h1>

<%= link_to 'Home', welcome_root_path %>

workspace/test_app/app/views/welcome/home.html.erb
		<!-- Main Title for Web page -->
		<h1>Welcome to my page</h1>
		
		<div id="row2">
			<ul>Below is a number of links to relevant Google pages:
				<li>Click <a href="http://www.google.com"> here</a> for google</li>
				<li>Click <a href="http://www.ultratech.com"> here</a> for Ultratech</li>
			</ul>
		</div>
		
		<!-- unordered list (bullets) -->
		<div id="row2">
			<ul>Animals:
				<li>Dogs</li>
				<li>Cats</li>
			</ul>
		
		<!-- ordered list (numbers) -->
			<ol>Food:
				<li>Chicken Burger</li>
				<li>Fish</li>
				<li>Steak</li>
			</ol>
		</div>

		
		<!-- Picture of a guitar -->
		<h4> This is a picture of a <b>guitar</b></h4>
	    <h4><img src="/assets/guitar3.jpg" /></h4>
		<h4><%= image_tag'/assets/guitar3.jpg' %></h4>
		

<%= link_to 'About', about_path %>