workspace/layout_example/config/routes.rb
Rails.application.routes.draw do
  resources :ebooks
  resources :books
  resources :users
  
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

workspace/layout_example/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workspace/layout_example/app/models/book.rb
class Book < ApplicationRecord
end

workspace/layout_example/app/models/ebook.rb
class Ebook < ApplicationRecord
end

workspace/layout_example/app/models/user.rb
class User < ApplicationRecord
end

workspace/layout_example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

workspace/layout_example/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:booktitle)
    end
end

workspace/layout_example/app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController
  before_action :set_ebook, only: [:show, :edit, :update, :destroy]

  # GET /ebooks
  # GET /ebooks.json
  def index
    @ebooks = Ebook.all
  end

  # GET /ebooks/1
  # GET /ebooks/1.json
  def show
  end

  # GET /ebooks/new
  def new
    @ebook = Ebook.new
  end

  # GET /ebooks/1/edit
  def edit
  end

  # POST /ebooks
  # POST /ebooks.json
  def create
    @ebook = Ebook.new(ebook_params)

    respond_to do |format|
      if @ebook.save
        format.html { redirect_to @ebook, notice: 'Ebook was successfully created.' }
        format.json { render :show, status: :created, location: @ebook }
      else
        format.html { render :new }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ebooks/1
  # PATCH/PUT /ebooks/1.json
  def update
    respond_to do |format|
      if @ebook.update(ebook_params)
        format.html { redirect_to @ebook, notice: 'Ebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @ebook }
      else
        format.html { render :edit }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebooks/1
  # DELETE /ebooks/1.json
  def destroy
    @ebook.destroy
    respond_to do |format|
      format.html { redirect_to ebooks_url, notice: 'Ebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ebook
      @ebook = Ebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ebook_params
      params.require(:ebook).permit(:title, :author, :price)
    end
end

workspace/layout_example/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

workspace/layout_example/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/layout_example/app/helpers/books_helper.rb
module BooksHelper
end

workspace/layout_example/app/helpers/ebooks_helper.rb
module EbooksHelper
end

workspace/layout_example/app/helpers/users_helper.rb
module UsersHelper
end

workspace/layout_example/app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :booktitle %>
    <%= form.text_field :booktitle, id: :book_booktitle %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

workspace/layout_example/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

workspace/layout_example/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Booktitle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.booktitle %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

workspace/layout_example/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

workspace/layout_example/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Booktitle:</strong>
  <%= @book.booktitle %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

workspace/layout_example/app/views/ebooks/_form.html.erb
<%= form_with(model: ebook, local: true) do |form| %>
  <% if ebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ebook.errors.count, "error") %> prohibited this ebook from being saved:</h2>

      <ul>
      <% ebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :ebook_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :ebook_author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ebook_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

workspace/layout_example/app/views/ebooks/edit.html.erb
<h1>Editing Ebook</h1>

<%= render 'form', ebook: @ebook %>

<%= link_to 'Show', @ebook %> |
<%= link_to 'Back', ebooks_path %>

workspace/layout_example/app/views/ebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ebooks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ebooks.each do |ebook| %>
      <tr>
        <td><%= ebook.title %></td>
        <td><%= ebook.author %></td>
        <td><%= ebook.price %></td>
        <td><%= link_to 'Show', ebook %></td>
        <td><%= link_to 'Edit', edit_ebook_path(ebook) %></td>
        <td><%= link_to 'Destroy', ebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ebook', new_ebook_path %>

workspace/layout_example/app/views/ebooks/new.html.erb
<h1>New Ebook</h1>

<%= render 'form', ebook: @ebook %>

<%= link_to 'Back', ebooks_path %>

workspace/layout_example/app/views/ebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ebook.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @ebook.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ebook.price %>
</p>

<%= link_to 'Edit', edit_ebook_path(@ebook) %> |
<%= link_to 'Back', ebooks_path %>

workspace/layout_example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LayoutExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div id='header'>
          <!-- Header Image Displayes here -->
          </div>
          <div id='menu'>
                 <!-- Header Image Displayes here -->
                 <div id="navbar">
      			 <ul>
          			 <li><a href="/users">Home</a></li>
          			 <li><a href="/books">Books</a></li>
          			 <li><a href="/ebooks">eBooks</a></li>
          			 <li><a href="/users">Register</a></li>
          			 <li><a href="#">Contact Us</a></li>
          			 <li><a href="#">Login</a></li>
      			</ul>
  		   </div>
        </div>
        <div id='container'>
          
            <div id='content'>
                <%= yield %>
            </div>
            
            <div id='first-column'>
            	<div class="searchbox">
            		<h2 class="BoxHeaders">Search</h2>
            		<input type="text" name="search" /><input type="submit" value="Search" />
            	</div>
            	<div class="box">
            		<h2 class="BoxHeaders">Special Offers</h2>
            		<img src="/assets/Books/Pict1.jpg" name="Rotating" id="Rotating1" alt="Special Offers ">

            		<script type="text/javascript">
            			RotateImages(1,0);
            		</script>
            	</div>
            	<div class="box">
            		<h2 class="BoxHeaders">Newly Published</h2>
            		<img src="/assets/Books/Pict1.jpg" alt="New Books">
            	</div>
             
            </div>
        </div>
        <div id='footer'>
            <h6 class="footertext">&copy; Online Stores NCI&trade; 2011</h6>
        </div>
  </body>
</html>

workspace/layout_example/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

workspace/layout_example/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

workspace/layout_example/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

workspace/layout_example/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

workspace/layout_example/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>